import type {Metadata} from "next";
import Link from 'next/link';
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import ThemeToggle from './components/ThemeToggle'; // Make sure this path is correct

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "HTS Rezepte",
    description: "Generated by create next app",
};

const globalNavigationItems = [
    {id: 'rezepte', text: 'Rezepte', href: '/burger'},
    {id: 'kategorien', text: 'Kategorien', href: '/categories'}, // Assuming you have this page
    {id: 'planner', text: 'Planner', href: '/meal-planner'}, // Assuming you have this page
    {id: 'koeche', text: 'Unsere Köche', href: '/koeche'},
    {id: 'image-showcase', text: 'Showcase', href: '/image-showcase'},
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased">
        <header className="sticky-top-bar">
            <div className="top-bar-logo">
                <Link href="/">HTS Rezepte</Link>
            </div>
            <div className="top-bar-controls">
                {/* Search bar is now inside top-bar-controls */}
                <nav className="top-bar-nav" aria-label="Main navigation">
                    {globalNavigationItems.map((item) => (
                        <Link key={item.id} href={item.href} className="top-bar-nav-button">
                            {item.text}
                        </Link>
                    ))}
                </nav>
                <div className="search-bar-container">
                    <input
                        type="search"
                        placeholder="Rezepte suchen..."
                        className="search-input"
                        aria-label="Search recipes"
                    />
                </div>

                <ThemeToggle/> {/* Theme toggle is also inside top-bar-controls */}
            </div>
        </header>

        <main className="main-page-content">
            {children}
        </main>
        </body>
        </html>
    );
}